version: '3.9'

services:
  apache:
    image: httpd:latest
    container_name: apache-app-container
    ports:
      - '80:80'
    volumes:
      - ./website:/usr/local/apache2/htdocs

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
